title: hypha
baseurl: ""
url: "https://hypha-rp.github.io"
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - github-pages
logo: assets/images/logo.png

markdown: kramdown
repository: hypha-rp/hypha-rp.github.io